### ISSUE TITLE
Milestone: Status Specs -> Vac RFCs

### ISSUE THREAD

**Issue by jimstir** [vacp2p/rfc-index#78]
Reference issue: https://github.com/vacp2p/rfc/issues/608
Author: kaiserd
This issue tracks the process of transforming [Status specs](https://specs.status.im/) to [Vac RFCs](https://rfc.vac.dev/). It also lists Vac `STATUS-` RFCs, that did not originally come from a Status spec.

### Status Specs to be Transformed

* [x] Status 1:1 Chat, and [5/SECURE-TRANSPORT](https://specs.status.im/spec/5)

  Has been transformed into [55/STATUS-1TO1-CHAT](https://rfc.vac.dev/spec/55/), generalizable parts have been split in
    - [53/WAKU2-X3DH](https://rfc.vac.dev/spec/53/)
    - [54/WAKU2-X3DH-SESSIONS](https://rfc.vac.dev/spec/54/)

* [x] [7/GROUP-CHAT](https://specs.status.im/draft/7)

  Covered in [55/STATUS-1TO1-CHAT](https://rfc.vac.dev/spec/55/)

### New Status RFCs

The following RFCs are new and not ported from existing Status specs.

* [ ] [59/STATUS-URL-DATA](https://github.com/vacp2p/rfc/pull/600)
* [ ] [60/STATUS-URL-SCHEME](https://github.com/vacp2p/rfc/pull/602)

### Status Scaling

* [57/STATUS-Simple-Scaling](https://rfc.vac.dev/spec/57/)

### Further Vac `STATUS-` RFCs

Review the following RFCs and check (1) if they are still relevant, and if yes, (2) if they need an update.

* [24/STATUS-CURATION](https://rfc.vac.dev/spec/24/)
* [28/STATUS-FEATURING](https://rfc.vac.dev/spec/28/)
